apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-grid-k8s-autoscaler-deployment
  labels:
    app: selenium-grid-k8s-autoscaler
    name: selenium-grid-k8s-autoscaler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-grid-k8s-autoscaler
  template:
    metadata:
      labels:
        app: selenium-grid-k8s-autoscaler
        name: selenium-grid-k8s-autoscaler
    spec:
      containers:
        - name: selenium-grid-k8s-autoscaler
          image: autoscaler-selenium-grid:1.0
          env:
            - name: k8s_host
              value: kubernetes.docker.internal:6443
            - name: k8s_token
              value: eyJhbGciOiJSUzI1NiIsImtpZCI6IklOR1I0STV2aHU4enRmdkZZSW5xUmRhdHJhWGpYaGItWnVJZTg4VXo1NG8ifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImF1dG8tc2NhbGUtcm9ib3Qtc2EiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiYXV0by1zY2FsZS1yb2JvdC1zYSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjNkYTBjZDEwLTAwMDQtNGNmZS1hZGQyLTBkZWU1MmI5MjY0NSIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWZhdWx0OmF1dG8tc2NhbGUtcm9ib3Qtc2EifQ.AGaK953kFQHRP3Peq7UWm_BwwWIJxO1t_USNy3JxXmYxJ7HqAM_ojMms75CSDRGkFW9spQSB2NnsxYsfxObzAypUvlGW9LtNYd5ZKjGx-nAkZhW1CGrnXRIwxDtTjGu2y9Po3wt6mF64CDvPc1I8e4rKaXjMYDkqGxV9nxTwJpGv9ZW1srpljpbNwEWGsaCkznpIoFqNN6ve1yAR-gp91PSaOJLn5GyZNt5nHmj6GudpexxDOX6FKzZ5WrqfoNybo2nFZWb-LHDeLr-M0ytlw3Kzwei04soM4nuaB0e98BS6mhFXkqIomQV40fHMkrBRwjI-VdzKoq7pLCasK5oRUQ
            - name: namespace
              value: default
            - name: chromeDeploymentName
              value: selenium-node-chrome
            - name: firefoxDeploymentName
              value: selenium-node-firefox
            - name: selenium_grid_host
              value: "selenium-hub-service.default.svc.cluster.local:4444"
            - name: ch_max_scale_limit
              value: "5"
            - name: ch_min_scale_limit
              value: "2"
            - name: ff_max_scale_limit
              value: "5"
            - name: ff_min_scale_limit
              value: "2"
            - name: grid_scale_check_frequency_in_sec
              value: "10"
            - name: server_port
              value: "8088"
            - name: logging_level_com_spr_k8sSelGrid
              value: "INFO"
