{{- if .Values.global.deployMyResourcesForSecret }}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: auto-scale-robot-sa
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: my-autoscaler
    meta.helm.sh/release-namespace: default
    
{{- end }}