apiVersion: v1
kind: Secret
metadata:
  name: auto-scale-robot-sa
  namespace: default
  annotations:
    kubernetes.io/service-account.name: auto-scale-robot-sa
type: kubernetes.io/service-account-token