apiVersion: v1
kind: Service
metadata:
  name: selenium-hub-service
  labels:
    app: selenium-hub
spec:
  selector:
    app: selenium-hub
  ports:
    - protocol: TCP
      port: 4444
      targetPort: 4444
  type: LoadBalancer